export type {
  Message,
  MessageRole,
  ContentBlock,
  TextBlock,
  ToolUseBlock,
  ToolResultBlock,
  MessageUsage,
  ToolCall,
  ModelCallResult,
  StreamEvent,
  StreamEventType,
  Terminal,
  AgenticConfig,
  PermissionRuleConfig,
  TaskModel,
  TaskStatus,
} from './types.js';

export { createStore, diffSubscribe, type Store, type DiffListener } from './state/store.js';
export {
  createSessionState,
  createSessionTracker,
  emptyUsage,
  formatMessagesForModel,
  type AgenticSessionState,
  type AgenticSessionEvents,
  type SessionTracker,
} from './state/session-state.js';

export {
  createPermission,
  compileGlobToRegex,
  normalizeForMatch,
  matchesAnyPermission,
  resolvePermission,
  isSandboxBackend,
  StateBackend,
  FilesystemBackend,
  compileGlob,
  countOccurrences,
  base64ToBytes,
  type BackendProtocol,
  type SandboxBackendProtocol,
  type FilesystemPermission,
  type StateBackendSnapshot,
  type FileInfo,
  type FileData,
  type FileOperationError,
  type ReadResult,
  type WriteResult,
  type EditResult,
  type LsResult,
  type GrepMatch,
  type GrepResult,
  type GlobResult,
  type UploadResult,
  type DownloadResult,
  type ExecuteResult,
} from './backends/index.js';

export {
  assembleMiddleware,
  applyExcludedMiddleware,
  mergeMiddlewareStacks,
  collectMiddlewareTools,
  collectMiddlewareSystemPromptContributions,
  findMiddleware,
  isMiddleware,
  TodoListMiddleware,
  FilesystemMiddleware,
  SummarizationMiddleware,
  MemoryMiddleware,
  loadMemoryFile,
  SkillsMiddleware,
  loadSkillFile as loadSkillFileMiddleware,
  parseSkillFrontmatter,
  PROTECTED_MIDDLEWARE,
  type AgentMiddleware,
  type MiddlewareContext,
  type TodoItem as MiddlewareTodoItem,
  type SummarizationMiddlewareOptions,
  type MemorySource,
  type MemoryFileEntry,
  type SkillSource,
  type SkillFileEntry,
} from './middleware/index.js';

export {
  buildTool,
  validateInputAgainstSchema,
  toolResultToBlock,
  findToolByName,
  toolMatchesName,
  type Tool,
  type ToolDef,
  type ToolInputSchema,
  type ToolPropertySchema,
  type ToolUseContext,
  type ToolCallProgress,
  type ToolResult,
  type PermissionDecision,
  type CanUseToolFn,
} from './tools/types.js';
export {
  getAllBaseTools,
  getTools,
  assembleToolPool,
  filterToolsByDenyRules,
  registerTool,
  registerTools,
  findTool,
  buildSimpleModePool,
  type ToolVisibility,
} from './tools/registry.js';
export {
  BashTool,
  FileReadTool,
  FileEditTool,
  FileWriteTool,
  GlobTool,
  GrepTool,
  WebFetchTool,
  TodoWriteTool,
  MemoryTool,
  AskUserQuestionTool,
  SleepTool,
  SubagentTool,
  isReadOnlyCommand,
  isDestructiveCommand,
  getTodos,
  type TodoItem,
} from './tools/implementations.js';

export {
  hasPermissionsToUseTool,
  createPermissionRuleSet,
  addPermissionRule,
  ruleMatches,
  normalizePermissionPattern,
  isSafetySensitiveInput,
  EMPTY_PERMISSION_RULE_SET,
  type PermissionMode,
  type PermissionRule,
  type PermissionRuleSet,
  type PermissionCheckContext,
} from './permissions/permissions.js';

export {
  getSystemContext,
  fetchSystemPromptParts,
  findProjectGuidance,
  readMemoryDir,
  getProjectGuidanceSearchPaths,
  type SystemContext,
  type SystemPromptParts,
} from './context/system-context.js';
export {
  renderToolSchema,
  renderToolsAsXml,
  buildSystemPrompt,
  buildMessagesForModel,
  renderMessagesAsText,
  describeSchema,
} from './context/prompt-builder.js';
export {
  shouldAutoCompact,
  compactConversation,
  summarizeMessages,
  selectCompactionCandidates,
  estimateTokensApprox,
  estimateMessageTokens,
  mergeUsage,
  getTokenEstimateForUsage,
  type CompactResult,
  type AutoCompactOptions,
} from './context/compaction.js';
export {
  assembleSystemPrompt,
  assembleSystemMessage,
  profileMatchesModel,
  findProfileForModel,
  applyProfileToolExclusions,
  type PromptProfile,
  type AssemblyInput,
  type AssemblyResult,
} from './context/prompt-assembly.js';

export {
  LLMClientAdapter,
  stripToolCallsFromText,
  type ModelCaller,
  type ModelCallOptions,
} from './model/caller.js';
export {
  parseToolCallsFromText,
  parseToolInput,
  parseKeyValuePairs,
  hasToolCallSyntax,
  renderToolCallXml,
} from './model/tool-parser.js';

export {
  checkTokenBudget,
  createTokenBudget,
  createContinuationTracker,
  recordContinuation,
  shouldStopContinuations,
  getMaxOutputTokensForModel,
  computeCostUsd,
  type TokenBudgetState,
  type ContinuationTracker,
} from './query/token-budget.js';
export {
  runTools,
  runToolUse,
  runToolsPartitioned,
  partitionToolCalls,
  createToolResultMessage,
  type ToolExecutionOptions,
  type ToolExecutionResult,
} from './query/tool-execution.js';
export {
  createStopHook,
  handleStopHooks,
  runAutoDream,
  MEMORY_EXTRACTION_HOOK,
  DREAM_TRIGGER_HOOK,
  type StopHook,
  type StopHookContext,
  type StopHookResult,
} from './query/stop-hooks.js';
export { queryLoop, type QueryLoopOptions, type QueryLoopState } from './query/loop.js';
export { QueryEngine, type QueryEngineConfig, type SubmitMessageOptions } from './query/engine.js';
export {
  compressContext,
  findTurnBoundaries,
  truncateToolResultBlocks,
  chunkMessagesByTokens,
  serializeMessagesForSummary,
  summarizeChunkWithRetry,
  createSummaryBoundaryMessage,
  DEFAULT_COMPRESS_OPTIONS,
  type CompressOptions,
  type CompressResult,
} from './query/compaction-engine.js';
export {
  repairToolCallArguments,
  parseJsonArgs,
  coerceValue,
  resolveEnumValue,
  deterministicToolCallId,
  deduplicateToolCalls,
  detectPathOverlap,
  type ArgRepair,
  type RepairResult,
  type DedupResult,
  type PathOverlap,
} from './query/tool-call-repair.js';
export {
  classifyError,
  normalizeErrorMessage,
  extractErrorCode,
  FailoverChain,
  type ErrorCategory,
  type ClassifiedError,
  type FallbackModel,
  type FailoverChainOptions,
  type ProbeResult,
  type FailoverChainStatus,
} from './query/failover.js';
export {
  LaneQueue,
  GLOBAL_LANE,
  DEFAULT_LANE_CAPACITY,
  createAbortError,
  type LaneEnqueueOptions,
  type LaneTask,
  type LaneQueueOptions,
  type LaneStats,
  type LaneQueueStatus,
} from './query/lane-queue.js';

export {
  HistoryManager,
  historyEntryToText,
  type HistoryEntry,
} from './history/history.js';
export {
  generateTaskId,
  LocalAgentTask,
  LocalShellTask,
  DreamTask,
  createTaskRegistry,
  taskToModel,
  taskSummary,
  type Task,
  type TaskContext,
  type TaskRegistry,
  type TaskType,
} from './tasks/tasks.js';
export {
  parseFrontmatter,
  skillFromFile,
  loadSkillsDir,
  loadSkillFile,
  renderSkillPrompt,
  validateSkillArgs,
  createSkillRegistry,
  renderSkillCatalog,
  BUNDLED_SKILLS,
  type SkillDefinition,
  type SkillRegistry,
  type LoadSkillsOptions,
} from './skills/skills.js';
export {
  AvailabilityRegistry,
  withTimeout,
  DEFAULT_AVAILABILITY_TTL_MS,
  type ProbeFn,
  type AvailabilityOptions,
  type AvailabilityEntry,
} from './tools/availability.js';
export {
  SubagentRegistry,
  createSubagentId,
  AsyncSubagentRegistry,
  createAsyncTaskId,
  type SubagentRecord,
  type SubagentStatus,
  type SubagentSpawnOptions,
  type SubagentRegistryOptions,
  type RegistrySnapshot,
  type RetryRecord,
  type AsyncTaskRecord,
  type AsyncTaskStatus,
  type AsyncTaskRunner,
  type AsyncLaunchOptions,
} from './subagents/index.js';
