/**
 * Tier I — Computer Science Intelligence.
 *
 * Concepts that should be permanent capabilities of the harness:
 * algorithms & complexity, data structures, operating systems,
 * networking, distributed systems. Each concept carries signals
 * (how to recognize relevance), triggers (when it activates),
 * guidance (what to check), antiPatterns (violations), and
 * provenance (where the knowledge comes from).
 */

import type { EngineeringConcept, TierId } from '../types.js';

const TIER: TierId = 'tier-01-cs';

const C = (
  id: string,
  name: string,
  family: string,
  definition: string,
  signals: string[],
  triggers: string[],
  guidance: string[],
  antiPatterns: string[],
  provenance: string[],
): EngineeringConcept => ({
  id: `cs.${id}`,
  tier: TIER,
  name,
  family,
  definition,
  signals,
  triggers,
  guidance,
  antiPatterns,
  weight: 1,
  provenance,
});

const CLRS = ['CLRS, Introduction to Algorithms, 4th ed.'];
const OSTEP = ['OSTEP (Operating Systems: Three Easy Pieces)'];
const TCP = ['TCP/IP Illustrated — Stevens'];

export const TIER_01_CS_CONCEPTS: EngineeringConcept[] = [
  /* ------------------------------------------------------------ */
  /* Algorithms & Complexity                                      */
  /* ------------------------------------------------------------ */
  C(
    'complexity.time',
    'Time Complexity',
    'algorithms',
    'Asymptotic growth of runtime with input size; the first filter for algorithmic adequacy, not the last.',
    ['big-o', 'complexity', 'scales', 'o(n', 'perf'],
    ['loop', 'iteration', 'benchmark', 'performance'],
    ['State the worst and expected case before choosing an approach.', 'Prefer the simplest structure with adequate bounds; do not chase asymptotics at constant-cost expense.'],
    ['Claiming a solution is fast without stating bounds; quadratic loops over unbounded input.'],
    CLRS,
  ),
  C(
    'complexity.space',
    'Space Complexity',
    'algorithms',
    'Memory growth with input size; often the binding constraint in real systems.',
    ['memory', 'ram', 'footprint', 'cache'],
    ['store', 'buffer', 'cache'],
    ['Check whether space scales with input or stays constant; large copies of hot data are a smell.', 'Prefer streaming or in-place when the working set cannot fit.'],
    ['Materializing full copies where a view or iterator suffices.'],
    CLRS,
  ),
  C(
    'complexity.cache',
    'Cache Complexity',
    'algorithms',
    'How an algorithm uses the memory hierarchy (L1/L2/LLC); cache misses often dominate runtime more than instruction count.',
    ['cache', 'locality', 'miss'],
    ['hot path', 'loop', 'access pattern'],
    ['Scan data in access order; block or tile nested loops so working sets fit cache lines.'],
    ['Random access over large arrays in a tight loop; pointer-chasing traversal where linear scan works.'],
    ['MIT 6.172 cache-oblivious algorithms; CLRS'],
  ),
  C(
    'complexity.branch-prediction',
    'Branch Prediction',
    'algorithms',
    'Modern CPUs speculatively execute branches; unpredictable branches (data-dependent) stall pipelines.',
    ['branch', 'predictable', 'random'],
    ['loop', 'hot path', 'sort'],
    ['Prefer predictable, monotone data layouts; avoid branch-per-element decisions driven by raw data.'],
    ['Branch-per-element on unsorted/random data in a hot loop; sorting to remove branches usually wins.'],
    ['CMU CS:APP (Computer Systems: A Programmer\u2019s Perspective)'],
  ),
  C(
    'complexity.locality',
    'Locality of Reference',
    'algorithms',
    'Temporal and spatial locality govern effective memory speed; the difference between cache-hot and cache-cold access.',
    ['locality', 'cache', 'sequential'],
    ['loop', 'array', 'traverse'],
    ['Make traversal sequential; group data accessed together into the same cache line; consider struct-of-arrays.'],
    ['Random access where sequential works; linked lists traversed on every operation.'],
    ['CS:APP; CLRS'],
  ),
  C(
    'complexity.amortized',
    'Amortized Complexity',
    'algorithms',
    'Average cost per operation over a worst-case sequence — the honest way to characterize dynamic structures.',
    ['amortized', 'average', 'amortize'],
    ['resize', 'grow', 'double', 'append'],
    ['Justify dynamic-resizing structures by amortized cost (e.g. growing arrays), not worst-case single ops.'],
    ['Rejecting a structure because one rare op is O(n) when amortized cost is O(1); unbounded capacity with no growth plan.'],
    CLRS,
  ),
  C(
    'complexity.parallel',
    'Parallel Complexity',
    'algorithms',
    'Speedup is bounded by serial fraction (Amdahl) and work/span; parallelism adds coordination cost.',
    ['parallel', 'thread', 'worker', 'concurrent'],
    ['promise.all', 'parallel', 'async', 'worker'],
    ['Compute the serial fraction before parallelizing; measure contention, not just throughput.'],
    ['Parallelizing the trivial part; unbounded fan-out without a coordination budget.'],
    ['Amdahl\u2019s Law; CLRS (parallel algorithms)'],
  ),
  C(
    'complexity.communication',
    'Communication Complexity',
    'algorithms',
    'The cost of moving data between participants (nodes, processes, threads) — often the dominant cost in distributed systems.',
    ['communication', 'round trip', 'rpc', 'overhead'],
    ['distributed', 'service', 'api call', 'rpc'],
    ['Count round trips as the primary cost of a distributed algorithm; batch and pipeline to reduce them.'],
    ['Chatty per-item requests where a batched protocol fits; ignoring message size growth.'],
    ['Kushilevitz & Nisan, Communication Complexity'],
  ),
  C(
    'complexity.streaming',
    'Streaming Algorithms',
    'algorithms',
    'Algorithms that process data in one or few passes with sublinear memory — for unbounded or huge inputs.',
    ['stream', 'single pass', 'online'],
    ['stream', 'infinite', 'log', 'sensor'],
    ['When input cannot fit or is endless, use sketches (count-min, hyperloglog), not full materialization.'],
    ['Buffering an unbounded stream to run a batch algorithm.'],
    ['Muthukrishnan, Data Streams: Algorithms and Applications'],
  ),
  C(
    'complexity.external-memory',
    'External-Memory Algorithms',
    'algorithms',
    'Algorithms designed for data larger than RAM: minimize block transfers between disk/SSD and memory.',
    ['external', 'disk', 'io', 'block'],
    ['large file', 'dataset', 'spill', 'sort'],
    ['When working sets exceed RAM, prefer B-tree/merge-sort style block-aware access over random small reads.'],
    ['mmap-everything and random-access large datasets as if they were in RAM.'],
    ['Aggarwal & Vitter, The Input/Output Complexity of Sorting'],
  ),

  /* ------------------------------------------------------------ */
  /* Data Structures                                               */
  /* ------------------------------------------------------------ */
  C(
    'data-structures.skip-list',
    'Skip List',
    'data-structures',
    'Probabilistic balanced list with O(log n) search/insert; simpler than a balanced tree and lock-friendly in concurrent settings.',
    ['skip list', 'ordered', 'rank'],
    ['sorted set', 'range query', 'concurrent'],
    ['Prefer a skip list when you need ordered ops plus cheap concurrency (e.g. in-memory key-value tiers).'],
    ['Building a balanced tree by hand where a skip list is simpler to verify.'],
    ['Pugh, Skip Lists: A Probabilistic Alternative to Balanced Trees'],
  ),
  C(
    'data-structures.b-tree',
    'B-Tree',
    'data-structures',
    'Balanced multi-way tree tuned for block storage: one node per page, wide fan-out, O(log_B n) I/O.',
    ['b-tree', 'index', 'disk'],
    ['index', 'database', 'sorted', 'disk'],
    ['Use B-trees (or B+ trees) for on-disk indexes and range queries; LSM for write-heavy loads.'],
    ['Hash index where range scans are required; b-tree where writes dominate.'],
    ['Comer, The Ubiquitous B-Tree; DDIA'],
  ),
  C(
    'data-structures.radix-tree',
    'Radix Tree',
    'data-structures',
    'Compressed trie over binary keys; O(k) lookups and prefix matching with compact storage.',
    ['radix', 'prefix', 'ip'],
    ['prefix', 'ip range', 'route'],
    ['Use radix trees for prefix/range lookups over fixed-width keys (routing tables, IP indexes).'],
    ['Hash map for prefix queries; scanning all keys for a prefix match.'],
    ['Morrison, PATRICIA — Practical Algorithm to Retrieve Information Coded in Alphanumeric'],
  ),
  C(
    'data-structures.trie',
    'Trie',
    'data-structures',
    'Tree over key prefixes; O(key length) lookups, prefix autocomplete, sharing of common prefixes.',
    ['trie', 'prefix', 'autocomplete'],
    ['autocomplete', 'dictionary', 'prefix'],
    ['Use a trie for prefix search and autocomplete where hash maps cannot answer prefix queries.'],
    ['Linear scan over dictionary for autocomplete; regex over every key per keystroke.'],
    ['CLRS; Fredkin, Trie Memory'],
  ),
  C(
    'data-structures.bloom-filter',
    'Bloom Filter',
    'data-structures',
    'Probabilistic membership with no false negatives and tunable false positives; constant memory regardless of elements.',
    ['bloom', 'probabilistic', 'membership'],
    ['cache', 'dedupe', 'exists check', 'seen'],
    ['Use a bloom filter where a false negative is forbidden and a small false-positive rate is acceptable (cache pre-filters, dedup).'],
    ['Exact set of millions of entries in RAM where a bloom filter is admissible; bloom filter where false negatives are not.'],
    ['Burton Bloom, Space/Time Trade-offs in Hash Coding'],
  ),
  C(
    'data-structures.cuckoo-filter',
    'Cuckoo Filter',
    'data-structures',
    'Bloom alternative with deletion support, better locality, and bounded load; supports counting for duplicates.',
    ['cuckoo', 'probabilistic', 'membership'],
    ['dedupe', 'delete', 'membership'],
    ['Prefer a cuckoo filter when deletions or count queries are needed alongside membership tests.'],
    ['Bloom filter where deletions are required (bloom cannot delete).'],
    ['Fan et al., Cuckoo Filter: Practically Better Than Bloom'],
  ),
  C(
    'data-structures.segment-tree',
    'Segment Tree',
    'data-structures',
    'Static/updateable range-query structure: O(log n) queries and updates over intervals (sum, min, max, gcd).',
    ['segment tree', 'range query'],
    ['range', 'interval', 'aggregate'],
    ['Use a segment tree when interval queries interleave with point updates.'],
    ['O(n) scans per range query on large arrays; sqrt decomposition where log structure fits.'],
    ['CLRS; competitive programming canon'],
  ),
  C(
    'data-structures.fenwick-tree',
    'Fenwick Tree',
    'data-structures',
    'Binary indexed tree: O(log n) prefix sums and updates with a tiny constant; less flexible than a segment tree.',
    ['fenwick', 'binary indexed'],
    ['prefix sum', 'cumulative'],
    ['Prefer a Fenwick tree for prefix-sum workloads: simpler, faster, less memory than a segment tree.'],
    ['Segment tree where only prefix sums are needed.'],
    ['Fenwick, A New Data Structure for Cumulative Frequency Tables'],
  ),
  C(
    'data-structures.rope',
    'Rope',
    'data-structures',
    'Binary tree over string segments for O(log n) concatenation, slicing, and editing of large text.',
    ['rope', 'string concat', 'text buffer'],
    ['string', 'text editor', 'concatenate'],
    ['Use ropes for large-text mutation workloads (editors, buffers); plain strings for short immutable text.'],
    ['Repeatedly concatenating large strings (O(n²)); splitting massive strings repeatedly.'],
    ['Boehm et al., Ropes: An Alternative to Strings'],
  ),
  C(
    'data-structures.deque',
    'Deque',
    'data-structures',
    'Double-ended queue with O(1) push/pop at both ends — the container for queues, stacks, sliding windows.',
    ['deque', 'queue', 'stack'],
    ['queue', 'buffer', 'window'],
    ['Prefer a deque (or ring buffer) for FIFO/LIFO workloads over array/string hacks.'],
    ['array.shift()/unshift() in a hot path (O(n) each); string used as a stack.'],
    ['CLRS'],
  ),
  C(
    'data-structures.ring-buffer',
    'Ring Buffer',
    'data-structures',
    'Fixed-capacity FIFO over a preallocated array; zero allocation per op, bounded memory, lock-free friendly.',
    ['ring buffer', 'circular', 'fifo'],
    ['buffer', 'queue', 'stream', 'producer'],
    ['Use a ring buffer for bounded streaming/queueing where allocation per item is unacceptable.'],
    ['Unbounded queues in producers/consumers; per-item allocation in a hot ingestion loop.'],
    ['Design patterns canon (bounded buffer)'],
  ),
  C(
    'data-structures.lsm-tree',
    'LSM Tree',
    'data-structures',
    'Log-structured merge tree: buffered writes flushed as sorted runs, merged in background — the write-optimized alternative to B-trees.',
    ['lsm', 'log structured', 'sstable'],
    ['write heavy', 'append', 'ingest', 'log'],
    ['Use LSM when writes dominate and reads can tolerate compaction latency (key-value stores, time series).'],
    ['B-tree where write amplification dominates; unbounded in-memory buffering of writes.'],
    ['O\u2019Neil et al., The Log-Structured Merge-Tree; DDIA'],
  ),
  C(
    'data-structures.immutable',
    'Immutable Data Structures',
    'data-structures',
    'Structures that never mutate in place; sharing makes updates cheap, makes concurrency and reasoning safe.',
    ['immutable', 'persistent'],
    ['concurrent', 'shared state', 'undo'],
    ['Use immutable structures where shared state crosses threads or time (undo, snapshots, event sourcing).'],
    ['Defensive copying to fake immutability; mutable shared state across async boundaries.'],
    ['Okasaki, Purely Functional Data Structures'],
  ),
  C(
    'data-structures.persistent',
    'Persistent Data Structures',
    'data-structures',
    'Versioned structures preserving all past states with structural sharing; O(log n) per version.',
    ['persistent', 'versioned', 'undo'],
    ['undo', 'history', 'snapshot'],
    ['Reach for persistent structures when you need cheap history (undo stacks, branching timelines).'],
    ['Copying entire collections per version; hand-rolled version tables.'],
    ['Okasaki, Purely Functional Data Structures'],
  ),

  /* ------------------------------------------------------------ */
  /* Operating Systems                                             */
  /* ------------------------------------------------------------ */
  C(
    'os.scheduling',
    'Scheduling',
    'os',
    'How the OS orders work: fairness vs throughput vs latency trade-offs; your code\u2019s threads are scheduled, not run. ',
    ['scheduling', 'priority', 'quantum'],
    ['thread', 'worker', 'cron', 'job'],
    ['Design for the scheduler: don\u2019t busy-wait, don\u2019t assume real-time guarantees without RTOS/priority inheritance.'],
    ['Busy-wait loops; assuming equal progress among threads.'],
    OSTEP,
  ),
  C(
    'os.numa',
    'NUMA',
    'os',
    'Non-uniform memory access: local memory is fast, remote memory crosses a bus; socket-aware placement matters at scale.',
    ['numa', 'socket', 'remote memory'],
    ['many cores', 'thread', 'large memory'],
    ['Pin threads to cores and keep their data local; count cross-socket traffic when scaling.'],
    ['Random thread placement with scattered working sets on multi-socket machines.'],
    ['Lameter, An Introduction to NUMA'],
  ),
  C(
    'os.memory-layout',
    'Memory Layout',
    'os',
    'Stack vs heap vs globals; layout determines locality, fragmentation, and overflow behavior.',
    ['memory layout', 'stack', 'heap'],
    ['allocation', 'buffer', 'recursion'],
    ['Know which region each allocation lives in; stack for bounded frames, heap for dynamic lifetime.'],
    ['Huge stack frames; unbounded recursion; allocations that outlive their scope.'],
    OSTEP,
  ),
  C(
    'os.virtual-memory',
    'Virtual Memory',
    'os',
    'Address translation gives processes isolated address spaces; page faults are the cost of laziness.',
    ['virtual memory', 'page fault', 'address space'],
    ['mmap', 'large data', 'allocation'],
    ['Account for demand paging when touching large maps: first touch pays the page fault.'],
    ['Touching every page of a huge mmap and expecting warm access; ignoring overcommit.'],
    OSTEP,
  ),
  C(
    'os.paging',
    'Paging',
    'os',
    'Pages move between RAM and swap; access patterns that thrash the TLB/page tables dominate runtime.',
    ['paging', 'swap', 'tlb'],
    ['large data', 'scan', 'memory'],
    ['Keep hot working sets resident; prefer 2MB huge pages for big contiguous scans.'],
    ['Random access across multi-GB datasets; assuming everything is resident.'],
    OSTEP,
  ),
  C(
    'os.cache-hierarchy',
    'Cache Hierarchy',
    'os',
    'L1/L2/LLC latencies differ by orders of magnitude; hierarchy-aware layouts make loops 10-100x faster.',
    ['cache hierarchy', 'l1', 'l2', 'llc'],
    ['hot loop', 'matrix', 'access pattern'],
    ['Order loops so innermost iterations walk contiguous memory; consider cache blocking for tiles.'],
    ['Row-vs-column transposed access in nested loops; data-dependent pointer chasing.'],
    ['CS:APP'],
  ),
  C(
    'os.synchronization',
    'Synchronization',
    'os',
    'Locks, atomics, and memory ordering; correct concurrency is a reasoning discipline, not a library call.',
    ['synchronization', 'mutex', 'atomic', 'lock'],
    ['thread', 'shared state', 'concurrent'],
    ['Establish the shared-state invariant and prove which operations preserve it; prefer message passing where possible.'],
    ['Lock-free claims without memory-ordering analysis; locking order deadlocks.'],
    OSTEP,
  ),
  C(
    'os.file-systems',
    'File Systems',
    'os',
    'On-disk structure determines I/O cost: block size, journaling, fsync semantics, directory growth.',
    ['file system', 'fsync', 'block'],
    ['write', 'save', 'journal', 'log'],
    ['Know when durability is required (fsync) and what it costs; batch small writes; watch directory-entry storms.'],
    ['fsync on every tiny write; assuming writes are durable without fsync.'],
    OSTEP,
  ),
  C(
    'os.syscalls',
    'Syscalls',
    'os',
    'User/kernel boundary crossings cost ~1µs; syscall amplification is a real, measurable overhead.',
    ['syscall', 'io', 'context switch'],
    ['read', 'write', 'open', 'stat'],
    ['Batch syscalls (readv/writev, io_uring, epoll); avoid stat-per-file scans.'],
    ['One syscall per byte; polling files instead of event-driven I/O.'],
    OSTEP,
  ),
  C(
    'os.processes',
    'Processes',
    'os',
    'Isolated execution units: crash isolation, IPC cost, startup cost, memory overhead.',
    ['process', 'spawn', 'fork'],
    ['spawn', 'process', 'worker'],
    ['Pay process overhead only for isolation or language boundaries; reuse long-lived processes.'],
    ['Spawning a process per request; assuming in-process behavior from out-of-process.'],
    OSTEP,
  ),
  C(
    'os.threads',
    'Threads',
    'os',
    'Shared-address-space concurrency: cheap to create, expensive to get wrong; context switches cost real time.',
    ['thread', 'goroutine', 'context switch'],
    ['thread', 'async', 'worker pool'],
    ['Match thread counts to cores and blocking profile; prefer pools over spawn-per-task.'],
    ['Unbounded thread creation; oversubscription; blocking calls in tiny threads.'],
    OSTEP,
  ),
  C(
    'os.signals',
    'Signals',
    'os',
    'Asynchronous OS notifications; unsafe in most code paths, racy by design, yet ubiquitous in daemons.',
    ['signal', 'sigterm', 'sigkill'],
    ['kill', 'signal', 'shutdown'],
    ['Handle termination signals with minimal async-safe work; delegate cleanup to a supervising loop.'],
    ['Complex cleanup inside signal handlers; ignoring SIGTERM on graceful shutdown.'],
    OSTEP,
  ),
  C(
    'os.ipc',
    'IPC',
    'os',
    'Inter-process communication: pipes, sockets, shared memory, message queues — each with cost and semantics.',
    ['ipc', 'pipe', 'shared memory', 'message queue'],
    ['process', 'worker', 'socket'],
    ['Match the IPC mechanism to data volume: shared memory for bulk, sockets for heterogeneity, pipes for streams.'],
    ['Shared memory without synchronization; serializing bulk data through JSON sockets.'],
    OSTEP,
  ),
  C(
    'os.lock-contention',
    'Lock Contention',
    'os',
    'When threads wait on a lock, the system pays queueing, cache-line ping-pong, and priority inversion.',
    ['lock contention', 'mutex', 'contended'],
    ['shared state', 'hot path', 'counter'],
    ['Measure contention before optimizing; shard, use read-write locks, atomics, or lock-free algorithms in that order.'],
    ['One global lock in a multi-threaded hot path; lock-free code without a memory model.'],
    OSTEP,
  ),

  /* ------------------------------------------------------------ */
  /* Networking                                                   */
  /* ------------------------------------------------------------ */
  C(
    'net.tcp-internals',
    'TCP Internals',
    'networking',
    'Reliable byte stream over lossy networks: windows, retransmission, timers, and the states behind every connection.',
    ['tcp', 'socket', 'connection'],
    ['socket', 'connect', 'network'],
    ['Reason from TCP state: backoff, timeouts, half-open connections; set sane keepalives and timeouts.'],
    ['Assuming TCP is a dumb pipe; infinite connection timeouts on a flaky network.'],
    TCP,
  ),
  C(
    'net.udp',
    'UDP',
    'networking',
    'Datagrams with no reliability: no retransmit, no ordering, no congestion control — correct only with an application protocol.',
    ['udp', 'datagram'],
    ['realtime', 'game', 'voip'],
    ['When using UDP, own reliability and ordering in the protocol, or accept loss.'],
    ['QUIC-like reliability reimplemented badly; UDP for what needs TCP.'],
    TCP,
  ),
  C(
    'net.quic',
    'QUIC',
    'networking',
    'UDP-based, TLS-inline, stream-multiplexed transport with connection migration; HTTP/3 runs on it.',
    ['quic', 'http/3'],
    ['http/3', 'mobile', 'multiplex'],
    ['Prefer QUIC/HTTP/3 where head-of-line blocking or connection migration matters.'],
    ['Many parallel TCP connections to emulate stream multiplexing.'],
    ['RFC 9000, QUIC: A UDP-Based Multiplexed and Secure Transport'],
  ),
  C(
    'net.http2',
    'HTTP/2',
    'networking',
    'Binary, multiplexed, header-compressed HTTP: one connection, many streams, no HOL blocking at the message level.',
    ['http/2', 'h2', 'multiplex'],
    ['grpc', 'http/2', 'streaming'],
    ['Use HTTP/2 for many concurrent requests over one connection; mind stream priority and flow control.'],
    ['Connection-per-request where multiplexing fits; ignoring HTTP/2 flow control.'],
    ['RFC 7540'],
  ),
  C(
    'net.http3',
    'HTTP/3',
    'networking',
    'HTTP over QUIC: removes head-of-line blocking even under packet loss — the default for modern clients.',
    ['http/3', 'quic'],
    ['http/3', 'mobile', 'lossy'],
    ['Enable HTTP/3 where clients support it and lossy networks matter.'],
    ['Treating HTTP/3 as optional forever while paying HOL blocking.'],
    ['RFC 9114'],
  ),
  C(
    'net.congestion-control',
    'Congestion Control',
    'networking',
    'The network\u2019s fairness machinery: TCP adapts to loss/latency; your load generator and retries must not fight it.',
    ['congestion', 'backoff', 'cubic'],
    ['retry', 'throughput', 'load test'],
    ['Respect backoff; avoid synchronized retry waves; test against real loss/latency profiles.'],
    ['Unbounded concurrent retries that amplify congestion; ignoring the congestion collapse lesson.'],
    ['Jacobson, Congestion Avoidance and Control'],
  ),
  C(
    'net.dns',
    'DNS',
    'networking',
    'A distributed, cached, failure-prone naming system: TTLs, caching layers, and resolver semantics affect every lookup.',
    ['dns', 'resolver', 'ttl'],
    ['domain', 'resolve', 'lookup'],
    ['Cache DNS with TTL awareness; design for resolution failure; avoid per-request resolution.'],
    ['Per-request DNS lookups; treating DNS as reliable and instant.'],
    ['RFC 1035; DNS and BIND — Liu & Albitz'],
  ),
  C(
    'net.tls',
    'TLS',
    'networking',
    'The transport security layer: handshake, cipher suites, session resumption, and the cost of every new handshake.',
    ['tls', 'ssl', 'handshake'],
    ['https', 'certificate', 'encrypt'],
    ['Resume sessions to avoid handshake cost; pin with care; verify certificates everywhere, including internal services.'],
    ['Disabling verification for convenience; no session resumption on high-churn connections.'],
    ['RFC 8446 (TLS 1.3)'],
  ),
  C(
    'net.certificates',
    'Certificates',
    'networking',
    'The PKI trust model: chains, expiration, revocation, and rotation — operational incidents hide here.',
    ['certificate', 'pki', 'ca'],
    ['cert', 'expire', 'rotation'],
    ['Automate rotation and expiry monitoring; keep chains short; know revocation behavior in your stack.'],
    ['Manual cert renewal with no alerting; long-lived certs in rotation-critical paths.'],
    ['RFC 5280; SSLLabs best practices'],
  ),
  C(
    'net.reverse-proxy',
    'Reverse Proxies',
    'networking',
    'The front door: termination, routing, buffering, rate limiting, and observability at the edge of your services.',
    ['reverse proxy', 'nginx', 'gateway'],
    ['proxy', 'gateway', 'load balancer'],
    ['Terminate TLS, centralize rate limiting and request logging at the proxy; keep it stateless and redundant.'],
    ['Client-facing TLS behind a single point of failure; business logic in proxy config.'],
    ['The NGINX Handbook; system design canon'],
  ),
  C(
    'net.service-discovery',
    'Service Discovery',
    'networking',
    'How services find each other: DNS, registries, and health-based routing; stale entries are the classic failure.',
    ['service discovery', 'registry', 'etcd'],
    ['discovery', 'registry', 'health check'],
    ['Tie discovery to health checks; expire stale registrations; tolerate registry outage.'],
    ['Caching addresses forever; crashing when the registry is down.'],
    ['DDIA'],
  ),
  C(
    'net.connection-pooling',
    'Connection Pooling',
    'networking',
    'Reuse expensive connections (TCP+TLS handshakes): bounded pools, idle eviction, and healthy checkout. ',
    ['connection pool', 'pool', 'max connections'],
    ['database', 'http client', 'connections'],
    ['Bound pools explicitly; validate connections on checkout; size against the backend\u2019s limit.'],
    ['Unbounded connections; stale connection reuse without validation; pool exhaustion cascades.'],
    ['DDIA'],
  ),
  C(
    'net.load-balancing',
    'Load Balancing',
    'networking',
    'Spreading load across replicas: hashing, least-connections, and the stickiness that breaks the spread.',
    ['load balancing', 'round robin', 'hashing'],
    ['replica', 'scale out', 'traffic'],
    ['Choose the algorithm for the workload (consistent hashing for caches, least-conn for CPU work); rehash carefully.'],
    ['Round-robin against hot shards; inconsistent hashing that invalidates caches on scale.'],
    ['DDIA'],
  ),
  C(
    'net.retry-storms',
    'Retry Storms',
    'networking',
    'Retry amplification: every layer retrying on failure multiplies load N^depth — the classic outage accelerant.',
    ['retry storm', 'thundering herd', 'retry'],
    ['retry', 'timeout', 'backoff'],
    ['Cap retry depth and fan-out; use jittered exponential backoff; cut off cascades at the edge.'],
    ['Synchronized immediate retries; every layer retrying independently; no cap on retry fan-out.'],
    ['AWS Architecture Blog: Timeout, Retry and Circuit Breaker Patterns'],
  ),

  /* ------------------------------------------------------------ */
  /* Distributed Systems                                          */
  /* ------------------------------------------------------------ */
  C(
    'dist.cap',
    'CAP Theorem',
    'distributed-systems',
    'Under partition, a system chooses consistency or availability — the trade-off is a design decision, not a bug.',
    ['cap theorem', 'consistency', 'availability'],
    ['distributed', 'replica', 'consistency'],
    ['Name the CAP choice explicitly per operation; partition detection + explicit behavior beats silent inconsistency.'],
    ['Claiming "eventually consistent" without a model; ignoring partitions because they are rare.'],
    ['Brewer, CAP Twelve Years Later; DDIA'],
  ),
  C(
    'dist.pacelc',
    'PACELC',
    'distributed-systems',
    'CAP + "Else, Latency or Consistency": even without partitions, every replica choice trades latency for consistency.',
    ['pacelc', 'latency', 'consistency'],
    ['replica', 'read replica', 'latency'],
    ['Decide the latency/consistency trade for the steady state, not just partitions.'],
    ['Read replicas with stale reads sold as consistent; unbounded replication lag.'],
    ['Abadi, Consistency Tradeoffs in Modern Distributed Database System Design'],
  ),
  C(
    'dist.consensus',
    'Consensus',
    'distributed-systems',
    'Agreement despite failures: the hardest distributed primitive; never hand-roll, always use a proven protocol. ',
    ['consensus', 'agreement', 'quorum'],
    ['leader', 'election', 'replication'],
    ['Use Raft/Paxos (or a managed service) for consensus; do not improvise with ad-hoc quorum math.'],
    ['Hand-written leader election; majority logic without quorum analysis.'],
    ['DDIA; Fischer, Lynch, Paterson (FLP)'],
  ),
  C(
    'dist.raft',
    'Raft',
    'distributed-systems',
    'Understandable consensus: leader election, log replication, safety via election restrictions.',
    ['raft', 'leader election', 'log replication'],
    ['raft', 'leader', 'replicate'],
    ['Prefer Raft for new consensus needs: analyzable, with mature libraries and a precise spec.'],
    ['Forking a Raft implementation to "simplify" it.'],
    ['Ongaro & Ousterhout, In Search of an Understandable Consensus Algorithm'],
  ),
  C(
    'dist.paxos',
    'Paxos',
    'distributed-systems',
    'The original consensus family: correct but notoriously subtle; the theoretical baseline.',
    ['paxos', 'multi-paxos', 'quorum'],
    ['consensus', 'quorum'],
    ['Respect Paxos-derived invariants when reviewing consensus code even if Raft is the implementation.'],
    ['Dismissing quorum reasoning because a system "looks" correct.'],
    ['Lamport, The Part-Time Parliament; DDIA'],
  ),
  C(
    'dist.event-sourcing',
    'Event Sourcing',
    'distributed-systems',
    'State is derived from an append-only event log: full history, replayability, and CQRS enablement at storage cost.',
    ['event sourcing', 'event log', 'append only'],
    ['event', 'audit', 'replay', 'ledger'],
    ['Use event sourcing when history, audit, and replay are first-class requirements; bound snapshot cadence.'],
    ['Event sourcing without snapshots; mutable events (never rewrite history).'],
    ['Fowler, Event Sourcing; DDIA'],
  ),
  C(
    'dist.cqrs',
    'CQRS',
    'distributed-systems',
    'Separate write and read models so each is optimized independently — a scaling tool with consistency costs.',
    ['cqrs', 'command query'],
    ['read model', 'write model', 'denormalize'],
    ['Apply CQRS when read and write shapes diverge badly; own the read-model lag semantics.'],
    ['CQRS for a CRUD app that needs no separate model; ignoring lag in read models.'],
    ['Fowler, CQRS'],
  ),
  C(
    'dist.crdt',
    'CRDT',
    'distributed-systems',
    'Conflict-free replicated data types: commutative/associative merges guarantee convergence without coordination.',
    ['crdt', 'conflict free', 'merge'],
    ['offline', 'sync', 'collaborative'],
    ['Use CRDTs for concurrent editing/sync where merges must converge without a coordinator.'],
    ['Last-write-wins everywhere; merge logic with hidden ordering assumptions.'],
    ['Shapiro et al., CRDTs for Eventually Consistent Systems'],
  ),
  C(
    'dist.vector-clocks',
    'Vector Clocks',
    'distributed-systems',
    'Capture causal history: if one clock dominates another, events are causally related; incomparable means concurrent.',
    ['vector clock', 'causal'],
    ['sync', 'conflict', 'version'],
    ['Use vector clocks where you must distinguish causal from concurrent updates.'],
    ['Timestamps as causality (clock skew breaks it); ignoring concurrent updates.'],
    ['Lamport; DDIA'],
  ),
  C(
    'dist.lamport-clocks',
    'Lamport Clocks',
    'distributed-systems',
    'Logical counters that preserve the happens-before partial order with a single integer per process.',
    ['lamport', 'logical clock'],
    ['ordering', 'happens before'],
    ['Use Lamport clocks for total-order approximations where causal structure can be coarse.'],
    ['Treating logical time as real time; total order claims from partial orders.'],
    ['Lamport, Time, Clocks, and the Ordering of Events in a Distributed System'],
  ),
  C(
    'dist.sagas',
    'Sagas',
    'distributed-systems',
    'Long-running transactions as sequences of local steps with compensating actions — the distributed transaction pattern.',
    ['saga', 'compensation', 'orchestration'],
    ['transaction', 'payment', 'order flow'],
    ['Design compensations for every step; define failure semantics per step (forward vs backward recovery).'],
    ['Distributed two-phase commits; sagas with no compensation path.'],
    ['Garcia-Molina & Salem, Sagas; DDIA'],
  ),
  C(
    'dist.exactly-once',
    'Exactly-Once Semantics',
    'distributed-systems',
    'The strongest delivery claim: in practice, exactly-once = at-least-once + dedup + idempotent effects.',
    ['exactly once', 'dedup', 'idempotent'],
    ['exactly once', 'delivery', 'message'],
    ['Implement idempotency keys and dedup storage; never rely on the transport for exactly-once.'],
    ['Claiming exactly-once from a queue alone; effects that duplicate on retry.'],
    ['DDIA'],
  ),
  C(
    'dist.at-least-once',
    'At-Least-Once Delivery',
    'distributed-systems',
    'The honest default: messages may duplicate, so consumers must be idempotent.',
    ['at least once', 'redelivery'],
    ['retry', 'delivery', 'queue'],
    ['Assume duplicates; make consumers idempotent; expose delivery semantics in docs.'],
    ['Consumers that assume at-most-once; double-apply on redelivery.'],
    ['DDIA'],
  ),
  C(
    'dist.idempotency',
    'Idempotency',
    'distributed-systems',
    'Repeated identical requests produce identical results — the key that makes retries safe everywhere.',
    ['idempotent', 'idempotency key'],
    ['retry', 'payment', 'webhook'],
    ['Design idempotency keys for mutating APIs; verify by key before applying effects.'],
    ['Retries that double-charge/double-create; idempotency only in tests.'],
    ['DDIA; Stripe API idempotency docs'],
  ),
  C(
    'dist.eventual-consistency',
    'Eventual Consistency',
    'distributed-systems',
    'Replicas converge given quiescence; the question is not whether, but how fast and with what window.',
    ['eventual consistency', 'replication lag'],
    ['replica', 'sync', 'consistent'],
    ['Quantify the convergence window; surface staleness in the UI/model where it matters.'],
    ['"Eventual" as a hand-wave with unbounded lag; stale reads in safety-critical paths.'],
    ['DDIA'],
  ),
  C(
    'dist.split-brain',
    'Split-Brain',
    'distributed-systems',
    'A partitioned cluster with multiple active leaders — the failure mode that corrupts data, not just availability.',
    ['split brain', 'fencing'],
    ['leader', 'quorum', 'failover'],
    ['Prevent split-brain with quorum+fencing (STONITH); test network partitions explicitly.'],
    ['Failover without fencing; quorum configurations that survive an even split.'],
    ['DDIA'],
  ),
  C(
    'dist.gossip',
    'Gossip Protocols',
    'distributed-systems',
    'Epidemic dissemination: O(log n) propagation, eventual convergence, resilient to churn — used for membership and state.',
    ['gossip', 'epidemic', 'membership'],
    ['cluster', 'membership', 'heartbeat'],
    ['Use gossip for cluster membership and failure detection at scale; understand convergence and messaging overhead.'],
    ['Central heartbeat at scale; gossip without failure-detection semantics.'],
    ['Van Renesse et al., A Gossip-Style Failure Detection Service'],
  ),
];

export function tier01CSConcepts(): EngineeringConcept[] {
  return TIER_01_CS_CONCEPTS.map((c) => ({ ...c }));
}
