/**
 * Tier II — Software Engineering Intelligence.
 *
 * Where current coding agents plateau: coupling, cohesion, modularity,
 * encapsulation, connascence, architecture drift, technical debt, and
 * the maintainability family. Refactoring and code-smell research ties
 * these concepts to long-term software quality (arXiv:2004.10777).
 */

import type { EngineeringConcept, TierId } from '../types.js';

const TIER: TierId = 'tier-02-se';

const C = (
  id: string,
  name: string,
  family: string,
  definition: string,
  signals: string[],
  triggers: string[],
  guidance: string[],
  antiPatterns: string[],
  provenance: string[],
): EngineeringConcept => ({
  id: `se.${id}`,
  tier: TIER,
  name,
  family,
  definition,
  signals,
  triggers,
  guidance,
  antiPatterns,
  weight: 1,
  provenance,
});

const APOSD = ['A Philosophy of Software Design — Ousterhout'] as const;
const CODE_COMPLETE = ['Code Complete — McConnell'] as const;
const CS_REVIEW = ['arXiv:2004.10777 — Code Smells and Refactoring: Tertiary Systematic Review'] as const;
const GITCLEAR = ['GitClear Maintainability Gap 2026'] as const;

export const TIER_02_SE_CONCEPTS: EngineeringConcept[] = [
  C(
    'coupling',
    'Coupling',
    'modularity',
    'How tightly modules depend on each other; high coupling makes change ripple and reasoning span modules.',
    ['coupling', 'dependency', 'imports'],
    ['import', 'require', 'module', 'interface'],
    ['Measure fan-in/fan-out per module; prefer stable, narrow dependencies and inversion at boundaries.'],
    ['Deep import graphs; modules reaching into each other\u2019s internals; god modules imported everywhere.'],
    [CS_REVIEW[0], GITCLEAR[0]],
  ),
  C(
    'cohesion',
    'Cohesion',
    'modularity',
    'How strongly the elements of a module belong together; high cohesion keeps one module = one responsibility.',
    ['cohesion', 'responsibility', 'module'],
    ['module', 'class', 'file'],
    ['Group by change reason: code that changes together should live together.'],
    ['Utility-bucket modules; classes mixing persistence, UI, and business rules.'],
    [CS_REVIEW[0]],
  ),
  C(
    'modularity',
    'Modularity',
    'modularity',
    'Decomposing a system into replaceable, independently comprehensible parts with explicit contracts.',
    ['modular', 'module', 'plugin'],
    ['module', 'package', 'boundary'],
    ['Design modules around stable interfaces with explicit contracts; verify each can evolve alone.'],
    ['Circular module dependencies; modules that cannot be tested in isolation.'],
    [APOSD[0]],
  ),
  C(
    'encapsulation',
    'Encapsulation',
    'modularity',
    'Hiding implementation behind an interface so internal choices remain changeable.',
    ['encapsulation', 'private', 'internal'],
    ['class', 'module', 'api'],
    ['Expose the minimal surface; keep internals private and swappable.'],
    ['Getters/setters that leak structure; exposing collections that bypass invariants.'],
    [APOSD[0]],
  ),
  C(
    'information-hiding',
    'Information Hiding',
    'modularity',
    'Secrets inside a module stay inside: the most likely change drivers (formats, protocols, policies) are hidden.',
    ['information hiding', 'secrets', 'details'],
    ['format', 'protocol', 'policy'],
    ['Identify the design secrets per module and hide them behind the interface.'],
    ['Leaking wire formats and storage schemas into callers.'],
    ['Parnas, On the Criteria To Be Used in Decomposing Systems into Modules'],
  ),
  C(
    'architectural-boundaries',
    'Architectural Boundaries',
    'modularity',
    'The seams between architectural layers/components; boundaries define where policies and mechanisms separate.',
    ['boundary', 'layer', 'port'],
    ['layer', 'adapter', 'boundary'],
    ['Define boundaries by policy vs mechanism; keep crossing costs explicit and dependencies pointing inward.'],
    ['Leaky abstractions across layers; dependencies that point outward (UI importing persistence).'],
    ['Clean Architecture — Martin'],
  ),
  C(
    'deep-modules',
    'Deep Modules',
    'modularity',
    'The best interfaces are deep: small interface, large hidden implementation (the Unix philosophy per module).',
    ['deep module', 'interface'],
    ['interface', 'api', 'module'],
    ['Prefer interfaces that hide a lot; a shallow module (big interface, little implementation) is a red flag.'],
    ['Pass-through modules that add indirection without hiding anything.'],
    [APOSD[0]],
  ),
  C(
    'cognitive-complexity',
    'Cognitive Complexity',
    'quality',
    'How hard the code is to understand for a human: nesting, boolean logic, and control flow that tax working memory.',
    ['cognitive complexity', 'nesting', 'readability'],
    ['nested', 'deep', 'complex'],
    ['Keep nesting shallow; extract conditions into named predicates; break long chains.'],
    ['Five-level nesting; compound boolean expressions with negations.'],
    ['SonarSource Cognitive Complexity', CODE_COMPLETE[0], CS_REVIEW[0]],
  ),
  C(
    'cyclomatic-complexity',
    'Cyclomatic Complexity',
    'quality',
    'Number of linearly independent paths through a function — the structural complexity of its control flow.',
    ['cyclomatic', 'branches', 'paths'],
    ['branch', 'case', 'if else'],
    ['Keep per-function branch count bounded; high cyclomatic complexity means split the function.'],
    ['Decision-dense functions that testers cannot cover exhaustively.'],
    ['McCabe, A Complexity Measure'],
  ),
  C(
    'connascence',
    'Connascence',
    'modularity',
    'Two elements are connascent if changing one requires changing the other; weaker connascence is better.',
    ['connascence', 'co-change'],
    ['rename', 'change', 'together'],
    ['Prefer connascence of name/type over position/meaning; minimize the distance of co-changing elements.'],
    ['Positional arguments for semantics; duplicated literals that must change together.'],
    ['Page-Jones, What Every Programmer Should Know About Object-Oriented Design'],
  ),
  C(
    'architecture-drift',
    'Architecture Drift',
    'evolution',
    'The slow divergence of implementation from intended architecture; invisible until it is a crisis.',
    ['architecture drift', 'divergence', 'conformance'],
    ['refactor', 'architecture', 'convention'],
    ['Verify architecture conformance mechanically (dependency rules, boundary tests) before drift compounds.'],
    ['Architecture diagrams that describe a system the code no longer is.'],
    ['Perry & Wolf, Foundations for the Study of Software Architecture'],
  ),
  C(
    'technical-debt',
    'Technical Debt',
    'evolution',
    'Deliberate or accidental shortcuts that accrue interest; the debt must be visible, quantified, and paid down.',
    ['technical debt', 'hack', 'todo', 'workaround'],
    ['todo', 'hack', 'quick fix', 'temporary'],
    ['Record debt with an owner and a payoff date; pay interest by tracking rework cost.'],
    ['Unlisted shortcuts that become load-bearing; perpetual "temporary" code.'],
    ['Cunningham, The WyCash Portfolio Management System; GITCLEAR'],
  ),
  C(
    'code-smells',
    'Code Smells',
    'quality',
    'Surface symptoms of deeper problems: duplication, long methods, feature envy, message chains — the readable signs.',
    ['code smell', 'duplication', 'long method'],
    ['duplicate', 'copy', 'long'],
    ['Treat smells as diagnostics, not rules: find the underlying design flaw each points at.'],
    ['Refactoring for its own sake; ignoring smells because "the tests pass".'],
    ['Fowler, Refactoring; CS_REVIEW'],
  ),
  C(
    'refactoring-opportunities',
    'Refactoring Opportunities',
    'evolution',
    'Behavior-preserving restructuring that keeps the system pliable; a backlog item, not a one-time event.',
    ['refactor', 'restructure', 'improve'],
    ['refactor', 'cleanup', 'simplify'],
    ['Refactor continuously in small steps with tests as the safety net; name the opportunity before executing.'],
    ['Big-bang rewrites; refactoring without behavioral verification.'],
    ['Fowler, Refactoring; GITCLEAR'],
  ),
  C(
    'change-amplification',
    'Change Amplification',
    'evolution',
    'The number of places one logical change must touch; the strongest single predictor of maintenance cost.',
    ['change amplification', 'touches', 'ripple'],
    ['change', 'touch', 'everywhere'],
    ['Ask "how many files does a typical change touch?" and shrink the answer; low amplification = high evolvability.'],
    ['Same constant/rule edited in N files per change; cascading find-replace rituals.'],
    ['APOSD; GITCLEAR'],
  ),
  C(
    'stability',
    'Stability',
    'evolution',
    'A module\u2019s resistance to breaking when its dependencies change; stable modules absorb change, not propagate it.',
    ['stability', 'stable', 'volatile'],
    ['dependency', 'change', 'interface'],
    ['Depend on stable abstractions; isolate volatile dependencies behind stable interfaces.'],
    ['Core modules depending on volatile libraries directly.'],
    ['Martin, Stability principle'],
  ),
  C(
    'extensibility',
    'Extensibility',
    'evolution',
    'Adding behavior without modifying existing code: open-closed through extension points, not edits.',
    ['extensible', 'extension', 'plugin'],
    ['new feature', 'extend', 'variant'],
    ['Provide extension points at anticipated variation axes; avoid speculative generality elsewhere.'],
    ['Plugin infrastructure for features that will never vary; editing core for each new case.'],
    ['Martin, Open-Closed Principle'],
  ),
  C(
    'testability',
    'Testability',
    'quality',
    'How easily a unit can be exercised in isolation; testability is designed in, not discovered in testing.',
    ['testability', 'mock', 'inject'],
    ['test', 'dependency', 'constructor'],
    ['Design seams (injection, ports) so every unit can be tested without the real world.'],
    ['Singletons and static state that cannot be isolated; tests that require the whole stack.'],
    [CS_REVIEW[0]],
  ),
  C(
    'maintainability',
    'Maintainability',
    'evolution',
    'The cost of keeping the system healthy over time: comprehension, modification, and repair at reasonable cost.',
    ['maintainability', 'maintain', 'legacy'],
    ['maintain', 'support', 'legacy'],
    ['Optimize for the maintainer\u2019s time: clarity, locality, and small modules beat cleverness.'],
    ['Write-only cleverness; documentation that describes intent the code no longer honors.'],
    ['ISO/IEC 25010; GITCLEAR'],
  ),
  C(
    'evolvability',
    'Evolvability',
    'evolution',
    'The system\u2019s ability to change direction cheaply: fitness for change over fitness for today.',
    ['evolvable', 'adapt', 'future'],
    ['roadmap', 'future', 'evolve'],
    ['Keep options open at known variation points; make the cost of changing direction visible.'],
    ['Foundational choices locked in without an exit ramp.'],
    ['Building Evolutionary Architectures — Ford'],
  ),
];

export function tier02SEConcepts(): EngineeringConcept[] {
  return TIER_02_SE_CONCEPTS.map((c) => ({ ...c }));
}
