export {
  parseFactsFence,
  renderFactsFence,
  effectiveFacts,
  isExpired,
  findTrajectory,
  flagRegression,
  FACTS_FENCE_BEGIN,
  FACTS_FENCE_END,
  FACT_KINDS,
  FACT_VISIBILITIES,
  FACT_NOTABILITIES,
  isFactKind,
  type FactRow,
  type FactKind,
  type FactVisibility,
  type FactNotability,
  type FactsFence,
  type FactParseResult,
  type TrajectoryPoint,
} from './facts-fence.js';
